### ISSUE TITLE
non critical error with spigot 1.9.4 and latest commit

### ISSUE THREAD

**Issue by frizzbee30** [andune/HomeSpawnPlus#102]
Hi, plugin is working fine for us, we just get frequent errors in console when it's used. Just for your attention for the next build!  :)

22.05 09:04:59 [Server] INFO at com.sun.proxy.$Proxy87.setBukkitBedHome(Unknown Source) ~[?:?]
22.05 09:04:59 [Server] INFO at com.andune.minecraft.hsp.shade.guice.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:37) ~[?:?]
22.05 09:04:59 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
22.05 09:04:59 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
22.05 09:04:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_31]
22.05 09:04:59 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
22.05 09:04:59 [Server] INFO at com.andune.minecraft.hsp.util.BedUtilsImpl.setBukkitBedHome(BedUtilsImpl.java:169) ~[?:?]
22.05 09:04:59 [Server] INFO at com.andune.minecraft.hsp.util.BedUtilsImpl.findBed(BedUtilsImpl.java:87) ~[?:?]
22.05 09:04:59 [Server] INFO at com.andune.minecraft.hsp.util.BedUtilsImpl.findBedRecursive(BedUtilsImpl.java:101) ~[?:?]
22.05 09:04:59 [Server] INFO Caused by: java.lang.NullPointerException
22.05 09:04:59 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_31]
22.05 09:04:59 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_31]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:11) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.PacketPlayInUseItem.a(SourceFile:55) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:887) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at net.minecraft.server.v1_9_R2.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:231) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-8a048fe-d8637df]
22.05 09:04:59 [Server] INFO org.bukkit.event.EventException
22.05 09:04:59 [Server] ERROR Could not pass event PlayerInteractEvent to HomeSpawnPlus v2.0.1-SNAPSHOT-b637

**Comment by frizzbee30** [comment]
outdated
