### ISSUE TITLE
SQLite name change error

### ISSUE THREAD

**Issue by seema84** [andune/HomeSpawnPlus#113]
if a player rename i get ->

[22:48:43 INFO]: Can not test connection as heartbeatsql is not set
[22:48:43 INFO]: Closing Connection[HomeSpawnPlus.1] psReuse[2] psCreate[4] psSize[4]
[22:48:43 ERROR]: Could not pass event PlayerJoinEvent to HomeSpawnPlus v2.0.2-b20161120-2000
org.bukkit.event.EventException
at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:103) ~[?:?]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: hsp_player.name)]
at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.andune.minecraft.hsp.storage.ebean.PlayerDAOEBean.savePlayer(PlayerDAOEBean.java:85) ~[?:?]
at com.andune.minecraft.hsp.util.NameChangeUtil.changeName(NameChangeUtil.java:55) ~[?:?]
at com.andune.minecraft.hsp.EventListener.playerJoin(EventListener.java:140) ~[?:?]
at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:101) ~[?:?]
... 15 more
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE]  A UNIQUE constraint failed (UNIQUE constraint failed: hsp_player.name)
at org.sqlite.core.DB.newSQLException(DB.java:909) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.sqlite.core.DB.newSQLException(DB.java:921) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.sqlite.core.DB.execute(DB.java:825) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.sqlite.core.DB.executeUpdate(DB.java:863) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:99) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.dml.UpdateHandler.execute(UpdateHandler.java:106) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.update(DmlBeanPersister.java:85) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeUpdateBean(DefaultPersistExecute.java:110) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:504) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:436) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619) ~[craftbukkit.jar:git-Spigot-96235ab-257d6cd]
at com.andune.minecraft.hsp.storage.ebean.PlayerDAOEBean.savePlayer(PlayerDAOEBean.java:85) ~[?:?]
at com.andune.minecraft.hsp.util.NameChangeUtil.changeName(NameChangeUtil.java:55) ~[?:?]
at com.andune.minecraft.hsp.EventListener.playerJoin(EventListener.java:140) ~[?:?]
at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:101) ~[?:?]
... 15 more

**Comment by frizzbee30** [comment]
we use MySQL with it, and have no issues at all with name changes. Since there is no further development on the plugin, then perhaps it is worth moving over to MySQL?
