### ISSUE TITLE
1.12-pre 5 broken

### ISSUE THREAD

**Issue by Math0424** [andune/HomeSpawnPlus#115]
does not work in 1.12 pre 5

**Comment by sorifiend** [comment]
What build did you use? You need to use b640 in 1.12.  Also please post your error log else no one can help you.

**Comment by sorifiend** [comment]
b640 can be found here: http://andune.com

**Comment by Math0424** [comment]
[20:49:15 ERROR]: [HomeSpawnPlus] Caught exception loading plugin, shutting down
com.andune.minecraft.hsp.shade.guice.CreationException: Guice creation errors:

1) Error in custom provider, java.lang.NullPointerException
  while locating com.andune.minecraft.hsp.guice.EbeanServerProvider
  at com.andune.minecraft.hsp.guice.BukkitModule.configure(BukkitModule.java:150)
  while locating io.ebean.EbeanServer
Caused by: java.lang.NullPointerException
        at com.andune.minecraft.hsp.guice.EbeanServerProvider.prepareDatabase(EbeanServerProvider.java:78)
        at com.andune.minecraft.hsp.guice.EbeanServerProvider.get(EbeanServerProvider.java:63)
        at com.andune.minecraft.hsp.guice.EbeanServerProvider.get(EbeanServerProvider.java:52)
        at com.andune.minecraft.hsp.shade.guice.internal.BoundProviderFactory.get(BoundProviderFactory.java:55)
        at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.andune.minecraft.hsp.shade.guice.Scopes$1$1.get(Scopes.java:65)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
        at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:95)
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:72)
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:62)
        at com.andune.minecraft.hsp.guice.BukkitInjectorFactory.createInjector(BukkitInjectorFactory.java:61)
        at com.andune.minecraft.hsp.HomeSpawnPlus.onEnable(HomeSpawnPlus.java:75)
        at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.onEnable(HomeSpawnPlusBukkit.java:78)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
        at java.lang.Thread.run(Unknown Source)

2) Error injecting constructor, java.lang.NullPointerException
  at com.andune.minecraft.hsp.storage.ebean.BukkitEBeanUtils.<init>(BukkitEBeanUtils.java:71)
  at com.andune.minecraft.hsp.storage.ebean.BukkitEBeanUtils.class(BukkitEBeanUtils.java:71)
  while locating com.andune.minecraft.hsp.storage.ebean.BukkitEBeanUtils
  while locating com.andune.minecraft.hsp.storage.ebean.EBeanUtils
    for field at com.andune.minecraft.hsp.guice.EbeanServerProvider.ebeanUtils(EbeanServerProvider.java:52)
  while locating com.andune.minecraft.hsp.guice.EbeanServerProvider
  at com.andune.minecraft.hsp.guice.BukkitModule.configure(BukkitModule.java:150)
  while locating io.ebean.EbeanServer
Caused by: java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at com.andune.minecraft.hsp.storage.ebean.BukkitEBeanUtils.<init>(BukkitEBeanUtils.java:62)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.andune.minecraft.hsp.shade.guice.internal.DefaultConstructionProxyFactory$2.newInstance(DefaultConstructionProxyFactory.java:85)
        at com.andune.minecraft.hsp.shade.guice.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
        at com.andune.minecraft.hsp.shade.guice.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.andune.minecraft.hsp.shade.guice.Scopes$1$1.get(Scopes.java:65)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.andune.minecraft.hsp.shade.guice.internal.FactoryProxy.get(FactoryProxy.java:54)
        at com.andune.minecraft.hsp.shade.guice.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
        at com.andune.minecraft.hsp.shade.guice.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
        at com.andune.minecraft.hsp.shade.guice.internal.ConstructorInjector.construct(ConstructorInjector.java:94)
        at com.andune.minecraft.hsp.shade.guice.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
        at com.andune.minecraft.hsp.shade.guice.internal.BoundProviderFactory.get(BoundProviderFactory.java:53)
        at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
        at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.andune.minecraft.hsp.shade.guice.Scopes$1$1.get(Scopes.java:65)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
        at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:95)
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:72)
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:62)
        at com.andune.minecraft.hsp.guice.BukkitInjectorFactory.createInjector(BukkitInjectorFactory.java:61)
        at com.andune.minecraft.hsp.HomeSpawnPlus.onEnable(HomeSpawnPlus.java:75)
        at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.onEnable(HomeSpawnPlusBukkit.java:78)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
        at java.lang.Thread.run(Unknown Source)

2 errors
        at com.andune.minecraft.hsp.shade.guice.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:183) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.shade.guice.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:95) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:72) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.shade.guice.Guice.createInjector(Guice.java:62) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.guice.BukkitInjectorFactory.createInjector(BukkitInjectorFactory.java:61) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.HomeSpawnPlus.onEnable(HomeSpawnPlus.java:75) ~[HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.onEnable(HomeSpawnPlusBukkit.java:78) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b640.jar:2.1.0-SNAPSHOT]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-60095c9-a479029]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-60095c9-a479029]
        at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-60095c9-a479029]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-60095c9-a479029]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-60095c9-a479029]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-60095c9-a479029]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-60095c9-a479029]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-60095c9-a479029]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-60095c9-a479029]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-60095c9-a479029]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[20:49:15 INFO]: [HomeSpawnPlus] Disabling HomeSpawnPlus v2.1.0-SNAPSHOT-b640

**Comment by sorifiend** [comment]
Looks like you are missing database info from your bukkit.yml

Add the following to the end of your bukkit.yml:
> database:
>   username: bukkit
>   driver: org.sqlite.JDBC
>   password: examplePassword
>   url: jdbc:sqlite:{DIR}{NAME}.db

Here is a copy from my bukkit.yml if you want to try copy it
> database:
>   username: bukkit
>   isolation: SERIALIZABLE
>   driver: org.sqlite.JDBC
>   password: examplePassword
>   url: jdbc:sqlite:{DIR}{NAME}.db

With the info above b640 starts find with 1.12pre5
