### ISSUE TITLE
ClassNotFound

### ISSUE THREAD

**Issue by seema84** [andune/HomeSpawnPlus#118]
[Server thread/WARN]: could not get type for name com.onarandombox.MultiverseCore.api.SafeTTeleporter from any class loader
com.andune.minecraft.hsp.shade.reflections.ReflectionsException: could not get type for name com.onarandombox.MultiverseCore.api.SafeTTeleporter
	at com.andune.minecraft.hsp.shade.reflections.ReflectionUtils.forName(ReflectionUtils.java:390) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.reflections.Reflections.expandSuperTypes(Reflections.java:381) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.reflections.Reflections.<init>(Reflections.java:126) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.reflections.Reflections.<init>(Reflections.java:168) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.reflections.Reflections.<init>(Reflections.java:141) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.guice.HSPModule.provideReflections(HSPModule.java:126) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at com.andune.minecraft.hsp.shade.guice.internal.ProviderMethod.get(ProviderMethod.java:104) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.Scopes$1$1.get(Scopes.java:65) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.ConstructorInjector.construct(ConstructorInjector.java:84) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1031) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.Scopes$1$1.get(Scopes.java:65) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:75) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:73) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.callInContext(InjectorImpl.java:1024) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:73) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:60) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.shade.guice.internal.InjectorImpl.injectMembers(InjectorImpl.java:944) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.HomeSpawnPlus.onEnable(HomeSpawnPlus.java:78) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.onEnable(HomeSpawnPlusBukkit.java:78) [HomeSpawnPlus-v2.1.0-SNAPSHOT-b642.jar:2.1.0-SNAPSHOT]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [craftbukkit.jar:git-Spigot-cd6ba67-a7d074c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: com.onarandombox.MultiverseCore.api.SafeTTeleporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
	at com.andune.minecraft.hsp.shade.reflections.ReflectionUtils.forName(ReflectionUtils.java:388) ~[?:?]
	... 46 more

**Comment by sorifiend** [comment]
We will need a little bit more info to help diagnose the issue:
1) Do you have MultiverseCore installed as a plugin on your server?
2) What is the MultiverseCore version and build number

**Comment by seema84** [comment]
no i dont use multiverse

config settings:
multiverseEnabled: false
safeTeleport: false

**Comment by sorifiend** [comment]
I just want to double check where you are setting those values:
Are you using the old big config.yml, or are you using the new seperate "core.yml"?

If you still have the old big config.yml then you should remove it, and instead use the new separate configs.

**Comment by seema84** [comment]
i use the core.yml build b642

**Comment by afroman84** [comment]
this happens when loading the plugin on server start: https://hastebin.com/ujiyuhujif.vbs
i can confirm this happens to me and i don't use multiverse too and i'm running build 642

thank you

**Comment by seema84** [comment]
sorifiend, can you do something?

**Comment by sorifiend** [comment]
Does the plugin still function and do a successful teleport? If so then I can maybe hide the error otherwise it will take a lot more digging (I couldn't work it out last time I looked).

**Comment by seema84** [comment]
Yes the teleport function works.
