### ISSUE TITLE
Could not pass event PlayerJoinEvent to HomeSpawnPlus v2.0-SNAPSHOT-b602

### ISSUE THREAD

**Issue by Okane84** [andune/HomeSpawnPlus#36]
I think that every player who changed his nickname now when joining creates this exception:

[17:33:31] [User Authenticator #304/INFO]: UUID of player Okane is 4e9de6e5-9a1d-440b-81bf-27c5be06f6e4
[17:33:31] [Server thread/INFO]: [VanishNoPacket] Okane disappeared.
[17:33:31] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to HomeSpawnPlus v2.0-SNAPSHOT-b602
org.bukkit.event.EventException
	at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:98) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerList.onPlayerJoin(PlayerList.java:263) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.PlayerList.a(PlayerList.java:148) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.LoginListener.b(LoginListener.java:109) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.LoginListener.c(LoginListener.java:41) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.NetworkManager.a(NetworkManager.java:159) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.ServerConnection.c(ServerConnection.java:82) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:785) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0]
Caused by: javax.persistence.PersistenceException: Unique expecting 0 or 1 rows but got [2]
	at com.avaje.ebeaninternal.server.core.DefaultServer.findUnique(DefaultServer.java:1294) ~[spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at com.avaje.ebeaninternal.server.querydefn.DefaultOrmQuery.findUnique(DefaultOrmQuery.java:922) ~[spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at com.avaje.ebeaninternal.util.DefaultExpressionList.findUnique(DefaultExpressionList.java:193) ~[spigot-1.8-25.jar:git-Spigot-899f5ee-1092acb]
	at com.andune.minecraft.hsp.storage.ebean.PlayerDAOEBean.findPlayerByUUID(PlayerDAOEBean.java:69) ~[?:?]
	at com.andune.minecraft.hsp.EventListener.playerJoin(EventListener.java:123) ~[?:?]
	at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher$1.execute(BukkitEventDispatcher.java:96) ~[?:?]
	... 14 more
[17:33:31] [Server thread/INFO]: Okane[/151.18.67.152:2926] logged in with entity id 1474237 at ([world] 10056.33039176391, 65.53033766108474, 6491.444821612718)

(sorry for not pastebining but it's just a few lines)

i suspect this happens with everyone who changed his nickname from minecraft.net.

**Comment by andune** [comment]
This should be fixed in the latest Jenkins build (609) that was built automatically after that last push. Please re-open case if still an issue or leave a comment to let me know it's fixed up for you.

**Comment by Okane84** [comment]
Thank you so much,  I'll try tomorrow and will report if no errors.

Il giorno Gio 5 Feb 2015 23:43 andune <notifications@github.com> ha scritto:
