### ISSUE TITLE
Its still trying to use ebeans tho i have yaml chosen.

### ISSUE THREAD

**Issue by Paxination** [andune/HomeSpawnPlus#73]
1.8.7 spigot

Build 634 of homespawnplus 2.0.

Its still trying to use ebeans even tho i have set it to YAML.

also, its putting all its configs in my servers root directory which is VERY ANNOYING.

http://puu.sh/iKlrC/39829855aa.png

[01:03:17] [Server thread/ERROR]: ebean.properties not found
[01:03:17] [Server thread/INFO]: DataSourcePool [HomeSpawnPlus] autoCommit[false] transIsolation[SERIALIZABLE] min[2] max[20]
[01:03:17] [Server thread/INFO]: SubClassFactory parent ClassLoader [org.bukkit.plugin.java.PluginClassLoader]
[01:03:17] [Server thread/INFO]: Entities enhanced[0] subclassed[7]
[01:03:18] [Server thread/ERROR]: Error registering MBean[Ebean:server=HomeSpawnPlus2]
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(Unknown Source) ~[?:1.7.0_75]
	at java.lang.SecurityManager.checkPermission(Unknown Source) ~[?:1.7.0_75]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(Unknown Source) ~[?:1.7.0_75]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source) ~[?:1.7.0_75]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source) ~[?:1.7.0_75]
	at com.avaje.ebeaninternal.server.core.DefaultServer.registerMBeans(DefaultServer.java:389) [DefaultServer.class:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:226) [DefaultServerFactory.class:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:64) [DefaultServerFactory.class:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) [EbeanServerFactory.class:?]
	at org.bukkit.plugin.java.JavaPlugin.init(JavaPlugin.java:362) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:509) [PluginClassLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) [JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.<init>(HomeSpawnPlusBukkit.java:54) [HomeSpawnPlus.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [?:1.7.0_75]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.7.0_75]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.7.0_75]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.7.0_75]
	at java.lang.Class.newInstance(Unknown Source) [?:1.7.0_75]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:201) [PluginClassLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:320) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.7.0_75]

**Comment by frizzbee30** [comment]
make a 'fake' ebeans.properties file, that may help :)  It also stored it in my root, which I'm not sure if it's related to not having the ebeans initially. i need to do a bit fo research when I have time on our test server.

(ebeans.properties does need to be in root btw)
