### ISSUE TITLE
/sethome command errors in 1.8.8

### ISSUE THREAD

**Issue by Omnixius** [andune/HomeSpawnPlus#86]
This plugin worked perfectly in 1.8.7
I then updated to the latest spigot build for 1.8.8 , to be exact this is what I get when I type /version

This server is running CraftBukkit Version
git-Spigot-db6de12-07c3001 (MC: 1.8.8)  
(Implementing API version 1.8.8-R0.1-SNAPSHOT)

The only change I made was updating the version of spigot from 1.8.7 to 1.8.8

**Now when people type /sethome they get this.**

A system error was encountered, please contact your administrator.
/sethome - sets your home to your current location
/sethome name - sets a home named 'name' at your current location

**In the console I see this:**

[11:44:07] [Server thread/INFO]: omnixius issued server command: /sethome
[11:44:07] [Server thread/WARN]: [HomeSpawnPlus] Caught exception in command /sethome
javax.persistence.PersistenceException: The existing transaction is still active?
	at com.avaje.ebeaninternal.server.transaction.TransactionMap$State.set(TransactionMap.java:97) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.transaction.DefaultTransactionThreadLocal.set(DefaultTransactionThreadLocal.java:55) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.transaction.DefaultTransactionScopeManager.set(DefaultTransactionScopeManager.java:41) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:858) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.andune.minecraft.hsp.storage.ebean.HomeDAOEBean.saveHome(HomeDAOEBean.java:171) ~[HomeSpawnPlus.jar:2.0.1-SNAPSHOT]
	at com.andune.minecraft.hsp.util.HomeUtil.setHome(HomeUtil.java:325) ~[HomeSpawnPlus.jar:2.0.1-SNAPSHOT]
	at com.andune.minecraft.hsp.commands.SetHome.execute(SetHome.java:111) ~[HomeSpawnPlus.jar:2.0.1-SNAPSHOT]
	at com.andune.minecraft.hsp.command.BaseCommand.execute(BaseCommand.java:129) [HomeSpawnPlus.jar:2.0.1-SNAPSHOT]
	at com.andune.minecraft.hsp.server.bukkit.command.BukkitCommandRegister$1.onCommand(BukkitCommandRegister.java:145) [HomeSpawnPlus.jar:2.0.1-SNAPSHOT]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40-internal]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]

**At some point of players trying and failing to set homes, eventually the /Home command will also start to fail to work.*

**The /home command generates this error.**

[04:36:54] [Server thread/INFO]: Blackbast issued server command: /home Myst
[04:36:57] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to HomeSpawnPlus v2.0.1-SNAPSHOT-b634
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40-internal]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: javax.persistence.PersistenceException: The existing transaction is still active?
	at com.avaje.ebeaninternal.server.transaction.TransactionMap$State.set(TransactionMap.java:97) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.transaction.DefaultTransactionThreadLocal.set(DefaultTransactionThreadLocal.java:55) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.transaction.DefaultTransactionScopeManager.set(DefaultTransactionScopeManager.java:41) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:858) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.andune.minecraft.hsp.storage.ebean.HomeDAOEBean.saveHome(HomeDAOEBean.java:171) ~[?:?]
	at com.andune.minecraft.hsp.util.HomeUtil.setHome(HomeUtil.java:325) ~[?:?]
	at com.andune.minecraft.hsp.util.BedUtilsImpl.doBedClick(BedUtilsImpl.java:229) ~[?:?]
	at com.andune.minecraft.hsp.EventListener.bedRightClick(EventListener.java:373) ~[?:?]
	at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher.onPlayerInteract(BukkitEventDispatcher.java:181) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	... 17 more
[04:37:03] [EbeanBackgroundThread/INFO]: DataSourcePool [HomeSpawnPlus] grow; id[HomeSpawnPlus.8] busy[9] max[20]
[04:37:22] [Server thread/WARN]: Tried to add entity Zombie with pending removal and duplicate UUID 38547934-b0a4-4e7c-9f9a-d9fd9c9bc8d2
[04:40:28] [Server thread/INFO]: Blackbast issued server command: /trails
[04:40:30] [Server thread/INFO]: Blackbast issued server command: /traill
[04:40:32] [Server thread/INFO]: Blackbast issued server command: /trail
[04:40:40] [Server thread/INFO]: Blackbast issued server command: /trail IconCrack
[04:40:52] [Server thread/INFO]: Blackbast issued server command: /trail snow
[04:41:11] [Server thread/INFO]: [VirtualPack] Saving user data...
[04:41:56] [Server thread/INFO]: Blackbast issued server command: /fly
[04:41:57] [Server thread/INFO]: Blackbast issued server command: /fly
[04:45:00] [Server thread/INFO]: Blackbast issued server command: /home Jungle
[04:45:01] [Server thread/WARN]: Tried to add entity Zombie with pending removal and duplicate UUID 38547934-b0a4-4e7c-9f9a-d9fd9c9bc8d2
[04:45:12] [Server thread/INFO]: Blackbast issued server command: /repair
[04:45:22] [Server thread/INFO]: Blackbast issued server command: /cp repair
[04:45:37] [Server thread/INFO]: Blackbast issued server command: /cp repair
[04:45:39] [Server thread/INFO]: Blackbast issued server command: /money
[04:45:51] [Server thread/INFO]: Blackbast issued server command: /c repair
[04:45:56] [Server thread/WARN]: Tried to add entity Zombie with pending removal and duplicate UUID 38547934-b0a4-4e7c-9f9a-d9fd9c9bc8d2
[04:46:11] [Server thread/INFO]: [VirtualPack] Saving user data...
[04:46:56] [Server thread/INFO]: Blackbast issued server command: /home Myst
[04:49:34] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to HomeSpawnPlus v2.0.1-SNAPSHOT-b634
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40-internal]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40-internal]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40-internal]
Caused by: javax.persistence.PersistenceException: The existing transaction is still active?
	at com.avaje.ebeaninternal.server.transaction.TransactionMap$State.set(TransactionMap.java:97) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.transaction.DefaultTransactionThreadLocal.set(DefaultTransactionThreadLocal.java:55) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.transaction.DefaultTransactionScopeManager.set(DefaultTransactionScopeManager.java:41) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.avaje.ebeaninternal.server.core.DefaultServer.beginTransaction(DefaultServer.java:858) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	at com.andune.minecraft.hsp.storage.ebean.HomeDAOEBean.saveHome(HomeDAOEBean.java:171) ~[?:?]
	at com.andune.minecraft.hsp.util.HomeUtil.setHome(HomeUtil.java:325) ~[?:?]
	at com.andune.minecraft.hsp.util.BedUtilsImpl.doBedClick(BedUtilsImpl.java:229) ~[?:?]
	at com.andune.minecraft.hsp.EventListener.bedRightClick(EventListener.java:373) ~[?:?]
	at com.andune.minecraft.hsp.server.bukkit.BukkitEventDispatcher.onPlayerInteract(BukkitEventDispatcher.java:181) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40-internal]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-07c3001]
	... 17 more

**I see this message in the log in many places. **

[04:50:03] [EbeanBackgroundThread/INFO]: DataSourcePool [HomeSpawnPlus] grow; id[HomeSpawnPlus.9] busy[10] max[20

And now something completely unexpected. As I typed all this out it suddenly dawned on me what the problem was.  I am going to go ahead and post this so the info might help somebody else.

The problem behind all of this is homespawnplus is looking for a file called ebeans.properties in the root directory of the server.   So I simply created a new file, named it ebeans.properties and placed it in the folder. For good measure I edited the file to say "I am a pointless file"
After rebooting the server ALL of the above errors and problems are resolved.

Hope this helps somebody else.

**Comment by andune** [comment]
Thanks for the detail and sharing here, Omni. It would be a pretty simple matter for HSP to check for the existence of the file and just create an empty one if it didn't exist. But I'd have to get my IDE up and running, crack open the code and test the fixes; something I have no time/motivation to do at this time.

So for now I will just leave your ticket open here so if anyone else runs into this issue, they will find this and can fix it the same way you did.
