### ISSUE TITLE
Spigot 1.9 getOnlinePlayers()

### ISSUE THREAD

**Issue by seema84** [andune/HomeSpawnPlus#87]
[00:48:09 ERROR]: Error occurred while disabling HomeSpawnPlus v2.0-b610 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.andune.minecraft.hsp.shade.commonlib.server.bukkit.BukkitServer.getOnlinePlayers(BukkitServer.j
ava:268) ~[?:?]
        at com.andune.minecraft.hsp.util.SpawnUtil.updateAllPlayerLocations(SpawnUtil.java:262) ~[?:?]
        at com.andune.minecraft.hsp.HomeSpawnPlus.onDisable(HomeSpawnPlus.java:100) ~[?:?]
        at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.onDisable(HomeSpawnPlusBukkit.java:121) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-3af46
05-ed8cef0]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:gi
t-Spigot-3af4605-ed8cef0]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.jar:g
it-Spigot-3af4605-ed8cef0]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.9.jar:
git-Spigot-3af4605-ed8cef0]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.disablePlugins(CraftServer.java:340) [spigot-1.9.jar:git
-Spigot-3af4605-ed8cef0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.stop(MinecraftServer.java:454) [spigot-1.9.jar:git-Spi
got-3af4605-ed8cef0]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:595) [spigot-1.9.jar:git-Spig
ot-3af4605-ed8cef0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]

**Comment by sorifiend** [comment]
Pull requests #88 - #90 should fix this, along side my pull requests 1 and 2 for https://github.com/andune/anduneCommonBukkitLib

@andune sorry about some of the tab formatting, i didn't realize until after i had submitted them

**Comment by andune** [comment]
merged sorifiend's changes. sorifiend, thank you for fixing and sending PRs. Latest build is on Jenkins, though I haven't tested at all. seema or sorifiend, can you download and confirm it fixes the issue?

**Comment by sorifiend** [comment]
The was an issue with one class I had missed, it should be patched in the latest PR #91

**Comment by sorifiend** [comment]
The latest build from Jenkins seems to be working perfectly.
This issue can now be closed.

**Comment by seema84** [comment]
I can confirm that.
