### ISSUE TITLE
i suddenly get this error, with all 1.9 versions and also 1.8 version on 1.9 latest server

### ISSUE THREAD

**Issue by freakyy85** [andune/HomeSpawnPlus#95]
[05:59:51] [Server thread/ERROR]: Could not load 'plugins/HomeSpawnPlus.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/joda/time/LocalDateTime
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugins(CraftServer.java:296) [spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:201) [spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.NoClassDefFoundError: org/joda/time/LocalDateTime
        at com.avaje.ebeaninternal.server.type.DefaultTypeManager.initialiseJodaTypes(DefaultTypeManager.java:623) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at com.avaje.ebeaninternal.server.type.DefaultTypeManager.<init>(DefaultTypeManager.java:163) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:132) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:209) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.plugin.java.JavaPlugin.init(JavaPlugin.java:344) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:128) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:67) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at com.andune.minecraft.hsp.HomeSpawnPlusBukkit.<init>(HomeSpawnPlusBukkit.java:54) ~[HomeSpawnPlus.jar:2.0]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_74]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_74]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_74]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_74]
        at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_74]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-build.jar:git-Spigot-104c8c8-e43b278]
        ... 6 more

**Comment by freakyy85** [comment]
nm its a bug in XRay Informer
